version: '3.8'

services:
  url-service:
    env_file:
        - ../../.env
    build:
      context: ../../services/url-service
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - postgres
      - redis

  postgres:
    env_file:
      - ../../.env
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  redis:
    env_file:
      - ../../.env
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"

volumes:
  pgdata: